### ISSUE TITLE
\n in valid() [final01]

### ISSUE THREAD

**Issue by maxmunzel** [DeerMichel/kit-assignment-tests#14]
I really think that the tests shouldn't expect un-escaped newlines as a part of the command to be valid. 
I won't be expected in the grading, it's quasi nonsense in the context of the task, almost all implementations of a command-line (e.g. bash) default to end commands with newlines and it really confuses newbies. 
Maybe just put them in a seperate "Optional - newline in arguments"-test?

**Comment by deermichel** [comment]
Yeah, you're right. I gonna comment out tests expecting '\n' to work. It shouldn't be considered as user input, although names consisting of spaces only don't make sense either 😄 .

**Comment by maxmunzel** [comment]
In general sense should be seen relative in the context of an in-memory only literature system ^^
