### ISSUE TITLE
no filling strategy in MatchThreeGameTest

### ISSUE THREAD

**Issue by JP97Org** [DeerMichel/kit-assignment-tests#33]
There is no filling strategy set in these tests:
initializeFillBoardTest()
moveAcceptTest()

**Comment by ghost** [comment]
It is currently unknown whether the FillingStrategy should be set "manually" for the board before a MatchThreeGame, or if the MatchThreeGame should set the FillingStrategy by itself. The tests are designed for the second variant.

**Comment by deermichel** [comment]
I think the first variant is right... but who knows...

**Comment by ghost** [comment]
I know who knows... There is this legendary website which is always painfully slow...
