### ISSUE TITLE
NullPointerException in MatchThreeBoard conflicts with A.1

### ISSUE THREAD

**Issue by Thunderbolt32** [DeerMichel/kit-assignment-tests#37]
> A.1
> Werden an eine Methode sonstige nicht-valide Parameter übergeben wird eine IllegalArgumentException geworfen.

 -> There must be no NullPointerException

Maybe some tests should be ignored.

**Comment by deermichel** [comment]
not sure - we had following discussion earlier: https://ilias.studium.kit.edu/ilias.php?ref_id=583580&cmdClass=ilobjforumgui&thr_pk=85028&cmd=viewThread&cmdNode=75:r6&baseClass=ilrepositorygui

... but feel free to ask in a new thread for clarification ;)
