### ISSUE TITLE
Problems with myTest3() in MyMaximumDeltaMatcherTest

### ISSUE THREAD

**Issue by NicoWeidmann** [DeerMichel/kit-assignment-tests#39]
First of all, I want to thank everyone who contributed to the tests so far. You are awesome ;)!

Now, when running the myTest3-Test, it fails for my with the following output:
```
EXPECTED: ; (1, 1), (2, 2), (0, 2)
ACTUAL: (1, 1), (2, 2), (0, 2)
```
The issue however is that the matchAll()-method of the Matcher "returns all matches found on the board starting from the given set of initial position". With the current implementation of the test, an empty Set<Position> is expected to be contained by the `Set<Set<Position>>` representing the matches, since one of the initial positions is empty. However, I personally think that the matcher, when starting from an empty position, should return an empty `Set<Set<Position>>`, and not a `Set<Set<Position>>` containing a single, empty `Set<Position>`, so that the actual output is the correct one.

What is Your opinion on that?

**Comment by verachekan** [comment]
Hi Nico, there was a discussion on forum on this topic. The trainers give 3 opportunities to manage with this case. Sorry, that I first wrote the tests and after that found that my solution is not the only one
Here is the answer of trainer: [answer](https://ilias.studium.kit.edu/ilias.php?ref_id=583580&cmdClass=ilobjforumgui&thr_pk=85272&type=frm&item_ref_id=583580&cmd=viewThread&cmdNode=75:r6&baseClass=ilrepositorygui)

**Comment by NicoWeidmann** [comment]
Alright, thank you, I haven't seen that post. Should we ignore this case then?

**Comment by verachekan** [comment]
Yeah, I think we could. This is not the first time, I am asked about the test, so let we just ignore it)

**Comment by NicoWeidmann** [comment]
I changed the affected Tests. See PR #40.
